- hosts: jenkins
  become: yes
  roles:
    - role: geerlingguy.jenkins
      vars:
        jenkins_plugins: ["git", "docker-workflow", "workflow-aggregator"]
    - role: geerlingguy.docker
  tasks:
  - name: add jenkins to docker group
    user:
      name: jenkins
      append: yes
      groups: docker
  - name: restart jenkins
    service:
      name: jenkins
      state: restarted
